print("hello \"alok\" world")
print('I \'am alok')
print("line A\nline B \n line C")
print("name\t dolat\t rathore")
print("this is single backslash\\")
print("this is double backslash\\\\")
print("this is alok\bk")